use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  formats:
    - json

server:
  base_url: "http://localhost"
  secret_key: "dummy"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true